backend:
  name: git-gateway
  branch: master

media_folder: content/assets
public_folder: ../assets

collections:
  - name: startpage
    label: Startpage
    folder: content/startpage
    create: true
    editor:
      preview: false
    fields:
      - { name: shorttitle, label: Short Title }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Preamble, name: text, widget: text }
          - { label: Image, name: image, widget: image, required: false }
          - { label: Button text, name: button, widget: string, required: false }
          - { label: Button link, name: buttonlink, widget: string, required: false }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Marketing", "Web", "Strategy"] }
      - { label: "Image", name: "image", widget: "file" }
      - { label: "Preamble", name: "preamble", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "video"
    label: "Video"
    folder: "content/video"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Marketing", "Web", "Strategy"] }
      - { label: "Image", name: "image", widget: "file" }
      - { label: "Preamble", name: "preamble", widget: "string" }
      - { label: "Video URL", name: "video-url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "footer"
    label: "Footer"
    folder: "content/footer"
    create: true
    editor:
     preview: false
    fields:
      - { label: "Small heading", name: "smallheading", widget: "string" }
      - { label: "Heading", name: "heading", widget: "string" }
      - name: col1
        label: Column 1
        widget: object
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Text, name: text, widget: markdown }
      - name: col2
        label: Column 2
        widget: object
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Text, name: text, widget: markdown }
      - name: col3
        label: Column 3
        widget: object
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Text, name: text, widget: markdown }
      - name: col4
        label: Column 4
        widget: object
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Text, name: text, widget: markdown }